# Setup
title:        CityBook
tagline:      Pretrazivi imenik sluzbi i majstora za popravke u stambenoj zgradi u gradu Zagrebu.
base_url:      "/citybook/"
paginate:     1

# About/contact
author:
  name:       Code for America
  url:        http://codeforamerica.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
